### ISSUE TITLE
运行“play_one('https://www.bilibili.com/video/BV1Bv4y1N7Gg')”时报错

### ISSUE THREAD

**Issue by RAINighty** [jcq15/bilibili_playcount#7]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_1644\149499368.py", line 33, in play_one
    element=driver.find_element_by_xpath("//button[@class='bilibili-player-video-btn-speed-name']")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

**Comment by RAINighty** [comment]
删除二倍速后依然报错
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_1644\252381054.py", line 34, in play_one
    Video_Time = driver.find_element(By.CSS_SELECTOR, "span.bilibili-player-video-time-total").text
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"span.bilibili-player-video-time-total"}
  (Session info: chrome=107.0.5304.88)
Stacktrace:
Backtrace:
	Ordinal0 [0x0141ACD3+2075859]
	Ordinal0 [0x013AEE61+1633889]
	Ordinal0 [0x012AB7BD+571325]
	Ordinal0 [0x012DAC2F+764975]
	Ordinal0 [0x012DAE1B+765467]
	Ordinal0 [0x0130D0F2+970994]
	Ordinal0 [0x012F7364+881508]
	Ordinal0 [0x0130B56A+963946]
	Ordinal0 [0x012F7136+880950]
	Ordinal0 [0x012CFEFD+720637]
	Ordinal0 [0x012D0F3F+724799]
	GetHandleVerifier [0x016CEED2+2769538]
	GetHandleVerifier [0x016C0D95+2711877]
	GetHandleVerifier [0x014AA03A+521194]
	GetHandleVerifier [0x014A8DA0+516432]
	Ordinal0 [0x013B682C+1665068]
	Ordinal0 [0x013BB128+1683752]
	Ordinal0 [0x013BB215+1683989]
	Ordinal0 [0x013C6484+1729668]
	BaseThreadInitThunk [0x75BD6A14+36]
	RtlInitializeExceptionChain [0x77AAA9FF+143]
	RtlInitializeExceptionChain [0x77AAA9CA+90]
