### ISSUE TITLE
File Load Error for Untitled.ipynb

### ISSUE THREAD

**Issue by Mazinrenown** [jcq15/bilibili_playcount#9]
![打开失败](https://github.com/jcq15/bilibili_playcount/assets/108333974/7e8a2fa1-3f15-4387-a767-46b9e723a3cc)

**Comment by Mazinrenown** [comment]
Traceback (most recent call last):
      File "D:\zhenzawu\python311\Lib\site-packages\tornado\web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "D:\zhenzawu\python311\Lib\site-packages\jupyter_server\services\contents\handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "D:\zhenzawu\python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 182, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "D:\zhenzawu\python311\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 873, in get
        model = await self._notebook_model(path, content=content)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\zhenzawu\python311\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 826, in _notebook_model
        nb = await self._read_notebook(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\zhenzawu\python311\Lib\site-packages\jupyter_server\services\contents\fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: D:\Download\bilibili_playcount-master\Untitled.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...'))
[W 2023-09-06 18:56:36.324 ServerApp] 400 GET /api/contents/Untitled.ipynb?type=notebook&content=1&1693997796295 (392d3044b495427dbcf11d4ed3880b5e@::1) 13.90ms referer=http://localhost:8888/notebooks/Untitled.ipynb

**Comment by Mazinrenown** [comment]
"            print(Video_Time)\n",
    "            Total_Second = Change_The_Time_Type(Video_Time)\n",
    "            print(Total_Second)\n",
    "\n",
    "            # 点击播放\n",
+    "           # element=driver.find_element_by_xpath(\"//div[@class='bpx-player-ctrl-btn bpx-player-ctrl-play']\")\n",
    "            # webdriver.ActionChains(driver).move_to_element(element).click(element).perform()\n",
    "\n",
    "            # 页面最小化\n",
    "            driver.minimize_window() \n",
    "\n",
    "            # 看完视频\n",



多了个加号 被阴了.jpg

**Comment by Mazinrenown** [comment]
![寄2](https://github.com/jcq15/bilibili_playcount/assets/108333974/bab64ebb-c922-4ed6-8aca-cfb5f312e70a)
 被阴了*2
